version: "3.8"

services:
  client:
    depends_on:
      - server
    build: ./client
    ports:
      - 3000:3000
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./client:/app

  server:
    build: ./server
    ports:
      - 3001:3001
    environment:
      DBURI: "${DBURI}"
    volumes:
      - ./server:/app